services:
  client:
    container_name: deep-sad-fl-client-${CLIENT_ID}
    image: riesal11/deep-sad-fl:multi
    volumes:
      - ./data/${CLIENTS}_client_setup/client_${CLIENT_ID}:/app/data
    ports:
      - "3000:3000"
    tty: true
    entrypoint:
      - ../docker-entrypoint-client.sh
