# syntax=docker/dockerfile:1

FROM continuumio/anaconda3:2024.06-1
WORKDIR /app
COPY requirements.txt .
RUN conda config --append channels conda-forge
RUN conda install --file ./requirements.txt
RUN pip install torch==2.4.1 --index-url https://download.pytorch.org/whl/cpu
RUN pip install torchvision==0.19.1 --index-url https://download.pytorch.org/whl/cpu
RUN pip install -U ray
RUN pip install -U "ray[data,train,tune,serve]"
COPY . .
WORKDIR /app/src
ARG PORT
ENV PORT=${PORT}
ENTRYPOINT ["../docker-entrypoint-backup.sh"]
EXPOSE ${PORT}