version: '3'

# includes server, 1 client, 1 backup and data distributor + kafka

services:
  server:
    container_name: deep-sad-fl-server
    volumes:
      - ./data/${CLIENTS}_client_setup/server:/app/data
      - ./log/${CLIENTS}_client_setup/server:/app/log
    build:
      context: .
      dockerfile: ./Dockerfile.server
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    tty: true

  client_1:
    container_name: deep-sad-fl-client-1
    image: riesal11/deep-sad-fl:final
    depends_on:
      - kafka
    volumes:
      - ./data/${CLIENTS}_client_setup/client_1:/app/data
      - ./log/${CLIENTS}_client_setup/client_1:/app/log
    ports:
      - "3000:3000"
    tty: true
    environment:
      - SEED=1
      - PORT=3000

  backup_client_1:
    container_name: deep-sad-fl-backup-1
    image: riesal11/deep-sad-fl-backup
    depends_on:
      - kafka
      - distributor
    volumes:
      - ./data/${CLIENTS}_client_setup/backup_1:/app/data
      - ./log/${CLIENTS}_client_setup/backup_1:/app/log
    ports:
      - "3002:3002"
    tty: true

  zookeeper:
    image: bitnami/zookeeper:3.9.1
    container_name: deep-sad-fl-zookeeper
    # to survive the container restart
    tmpfs: "/zktmp"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7.0
    container_name: deep-sad-fl-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      # change <server_ip> to actual server ip
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://<server_ip>:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      # optional - enable topic auto create
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka_data:/bitnami/kafka

  distributor:
    container_name: deep-sad-fl-distributor
    depends_on:
      - zookeeper
      - kafka
    build:
      context: .
      dockerfile: ./Dockerfile.distributor
    volumes:
      - ./data/${CLIENTS}_client_setup/streams:/app/data
    ports:
      - "4000:4000"
    tty: true

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: deep-sad-fl-kafka-ui
    depends_on:
      - kafka

    ports:
      - "9000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

volumes:
  kafka_data:
    driver: local