services:
  server:
    container_name: deep-sad-fl-server
    build: .
    volumes:
      - ./data/3_client_setup/server:/app/data
      - ./log/3_client_setup/server:/app/log
    ports:
      - "8080:8080"
    tty: true
    entrypoint:
      - ../docker-entrypoint-server.sh
